### ISSUE TITLE
No releases on packagist.org

### ISSUE THREAD

**Issue by mundschenk-at** [GaryJones/Gamajo-Dashboard-Glancer#11]
I'm not sure why, but none of the released versions show up on [packagist.org](https://packagist.org/packages/gamajo/dashboard-glancer), only the development branch.

**Comment by GaryJones** [comment]
Did a manual update at Packagist, and now at least 1.0.4 is showing up (but not older tags).

Thanks for letting me know :-)

**Comment by GaryJones** [comment]
Ah, this package didn't _have_ a `composer.json` until `1.0.4`, so even if Packagist can look at older commits, the `composer.json` didn't exist in `1.0.3`, `1.0.2`, `1.0.1`, etc.
