### ISSUE TITLE
Feature request: change icons to match post type icon

### ISSUE THREAD

**Issue by helgatheviking** [GaryJones/Gamajo-Dashboard-Glancer#7]
The WordPress dashboard.css file seems to be responsible for the icons in the "at a glance" widget. But it just gives a hollow circle for any custom post types

![image](https://cloud.githubusercontent.com/assets/507025/9831780/02c1ae02-5932-11e5-998e-9922affbf254.png)

I don't know if it would work here, but it'd be great if the class could somehow set the CSS if the post type's `menu_icon` is set. 
![image](https://cloud.githubusercontent.com/assets/507025/9831786/140745c8-5932-11e5-9964-58b4539458a2.png)

**Comment by GaryJones** [comment]
I like that idea. I'm currently away, so won't be able to look at this for a while. If you can spot what's needed, then do a PR, and I can build on that.

**Comment by helgatheviking** [comment]
Upon further investigation, I am not sure it is even possible. the `dashboard.css` stylesheet is forcing the round circle via the following rule:

```
#dashboard_right_now li a:before, #dashboard_right_now li span:before {
    content: '\f159';
    font: normal 20px/1 'dashicons';
    speak: none;
    display: block;
    float: left;
    margin: 0 5px 0 0;
    padding: 0;
    text-indent: 0;
    text-align: center;
    position: relative;
    -webkit-font-smoothing: antialiased;
    text-decoration: none !important;
}
```

and even changing the classes on the link that is created by Dashboard Glancer to

```<a href="edit.php?post_status=publish&amp;post_type=document" class="dashicons-before dashicons-book-alt">15 Documents</a>```

Does not get the correct icon since the `dashboard.css` is *too* specific. I think doing this easily on your side would require a change to core (to always use dashicon classes on the links and then modify the CSS to account for it). My experience with that is it could take 5 years, so I'm just going to add my own little style rule to `admin_head`. 

```
function fix_glance_icon() { ?>
		<style>#dashboard_right_now .document-count a:before { content: '\f331'; }</style>
	<?php
	}
add_action( 'admin_head', 'fix_glance_icon' );
```

**Comment by GaryJones** [comment]
Thanks for looking. When I'm home, I'll see if I can cobble something together.

**Comment by GaryJones** [comment]
I've come to the same conclusion as you did. Definitely needs a change in core.

**Comment by GaryJones** [comment]
@helgatheviking: https://core.trac.wordpress.org/ticket/33714#comment:8

**Comment by helgatheviking** [comment]
Sweet! Nice work.

**Comment by robincornett** [comment]
I just used the glancer template today for the first time and THANK YOU. Ran into this also. I'm rolling the glancer into a functionality plugin, but I think the way I've added the icon to the dashboard could be implemented into your class. Here's what I have:

```
add_action( 'admin_enqueue_scripts', array( $this->admin, 'admin_css' ) );
public function admin_css() {
	$screen = get_current_screen();
	if ( ! in_array( $screen->base, array( 'dashboard' ) ) ) {
	return;
	}
	$post_types = apply_filters( 'gamajo_glancer_icons', array() );
	if ( ! $post_types ) {
	return;
	}
	echo '<style type="text/css">';
		foreach ( $post_types as $post_type ) {
		printf( '#dashboard_right_now .%s-count a:before { content: "%s"; }', $post_type['name'], $post_type['icon'] );
		}
		echo '</style>';
}
```

That's the bit I would add to your class. Then your users can do something like this to get the icon to properly show:

```
add_filter( 'gamajo_glancer_icons', 'prefix_add_glancer_icons' );
function prefix_add_glancer_icons( $post_types ) {
	$post_types[] = array(
		'name' => 'my-cpt',
		'icon' => '\f307',
	);
	return $post_types;
}
```

I've added the former pretty much exactly as is to my functionality plugin, and then have used the latter in several other plugins, and it seems to be working very nicely for me, so I thought I would suggest it.

**Comment by GaryJones** [comment]
Thanks for sharing that Robin. I'll take a look into what you've done. Only today did I look at my client's dashboard and wondered when I might find time to fix this.

![screenshot 2016-02-23 17 15 59](https://cloud.githubusercontent.com/assets/88371/13259884/33e2a946-da51-11e5-9ccb-89975da0f72d.png)

**Comment by robincornett** [comment]
My updated dashboard:

![image](https://cloud.githubusercontent.com/assets/4853066/13260073/fdb1d762-da27-11e5-97c0-c11c5633a5fe.png)

The Glancer class worked beautifully. Made the whole process so much easier. Thank you!

**Comment by GaryJones** [comment]
With inspiration from @robincornett's code, I've got automatic dashicons working:

![screenshot 2016-05-15 22 37 11](https://cloud.githubusercontent.com/assets/88371/15276923/a86d66b6-1aed-11e6-8cec-44fe9bc3b7f1.png)

There may still be edge cases to test, such as post types that have no menu_icon, or one that doesn't have it set as a dashicon, but @helgatheviking and @robincornett, could you please give the `icons` branch a go? You should be able to drop [this version](https://github.com/GaryJones/Gamajo-Dashboard-Glancer/blob/icons/class-gamajo-dashboard-glancer.php) in as a replacement for your existing lib file. Thanks.

**Comment by robincornett** [comment]
The automatic bit is working nicely, which is awesome. But the inline style doesn't seem to be loading for me at all, so I'm getting both a dashicon in black (?) and then the circle in the icon grey color.

![image](https://cloud.githubusercontent.com/assets/4853066/15277466/601aa6ae-1ad3-11e6-9436-c2f748e41048.png)

(both in trunk and 4.5.3alpha)

Also wondering why you are adding the dashicon class and icon to the `<li>` element rather than `<a>`, as the default post types do, although some poking at it suggests that WP won't let the `dashicons-before` class override the `#dashboard_right_now li a:before` already set, so never mind, I suppose. Overall, it's certainly easier than what I was doing.

**Comment by GaryJones** [comment]
The presence of the circle, and the black colour of the dashicon certainly suggests the dashboard internal style is not being added. Can you debug to find out why?

**Comment by robincornett** [comment]
In Query Monitor, I see the `dashboard_css` method being called, but it's not actually outputting anything. I've put in a `var_dump()` at the beginning of it and that isn't outputting anything either. No errors. Deactivated all plugins except for the one holding this class, reset theme to Twenty Sixteen, then activated a plugin with just one function to register a CPT. Added your sample function to add it to the Dashboard, still same results. Do you have more debugging things you'd suggest I try?

**Comment by GaryJones** [comment]
I just tried in 4.6 alpha branch, and it seems to work:

![screenshot 2016-05-16 14 08 55](https://cloud.githubusercontent.com/assets/88371/15290348/c5a67272-1b6f-11e6-83e4-7ef77c8dbe78.png)

Do make sure that you have at least one published item of the CPT you are adding - it won't show up otherwise.

**Comment by robincornett** [comment]
I really don't know why it's not working for me:
![image](https://cloud.githubusercontent.com/assets/4853066/15293518/5e22f76a-1b56-11e6-8557-2a412941ff8c.png)
I've also tried adding an inline style echo at the beginning of the dashboard method to override the body background color to red, so it would be immediately evident, and before the early return happens, and that's not outputting either.

**Comment by GaryJones** [comment]
@robincornett The `dashboard_css()` is hooked into the `admin_enqueue_scripts`. Perhaps change that to something like `admin_print_styles` (later hook), or change the priority? Does it definitely not appear in your source? Mine appears right after the `viewport` meta tag, before the standard `load-styles.php` admin CSS is referenced; so it might be a CSS cascading issue for you, rather than it be a PHP issue to make it not get sent to the source.

**Comment by robincornett** [comment]
I've checked the source code and tried changing the hook to later, earlier; tried changing priority as well. At this point the only way I've gotten it to work is to call it in the same function as adding the CPT, so:

```php
add_action( 'dashboard_glance_items', 'prefix_add_dashboard_counts' );
function prefix_add_dashboard_counts() {
	$glancer = new Gamajo_Dashboard_Glancer;
	$glancer->add( 'jetpack-testimonial' ); // show only published "my-cpt" entries
	$glancer->dashboard_css();
}
```

Which is certainly not right. Have gotten same behavior on two machines, one with the class in a plugin, one with the class in mu-plugins, also confirming there are no other instances of the class being loaded.

**Comment by GaryJones** [comment]
> I've checked the source code

And was the internal style sheet present or not?

**Comment by robincornett** [comment]
It only showed in the source code when I added it using `$glancer->dashboard_css();`.

**Comment by GaryJones** [comment]
This has been merged into `master` and the latest `tag`. I couldn't explain why it's not working for @robincornett, as it's working for me, so I'll leave it be unless someone else opens a new ticket.
