### ISSUE TITLE
Error with php7?

### ISSUE THREAD

**Issue by j-gardner** [GaryJones/Gamajo-Dashboard-Glancer#8]
Thanks for your work on this library.

A user of one of my plugins noted he's receiving the following notices with his site now that it's running on php7:
`
Notice: Array to string conversion in D:\wamp\www\wp\wp-content\plugins\arconix-faq\includes\class-gamajo-dashboard-glancer.php on line 123

Notice: Undefined property: stdClass::$Array in D:\wamp\www\wp\wp-content\plugins\arconix-faq\includes\class-gamajo-dashboard-glancer.php on line 123
`

**Comment by GaryJones** [comment]
What version of Glancer does your plugin use?

**Comment by j-gardner** [comment]
Yeah, that would help, wouldn't it... v1.0. After looking that up I realized, of course, that you already fixed that issue in v1.0.1. I feel dumb now.
